name: Python Workflow

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USERNAME : ${{ secrets.USERNAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
          
            cd /home/ubuntu/ascendbot &&
            git pull origin master &&
            python -m pip install --upgrade pip &&
            pip install -r requirements.txt &&
            python3 tradingbot.py &&

             

