name: Python Workflow

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME  }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}

        script: |
          cd /home/ubuntu/ascendbot &&
          git pull &&
          pip install -r requirements.txt &&
          python3 tradingbot.py &&






             

